steps:
  - command: scripts/downloads.sh
    name: "Download :buildkite: assets"
    agents:
      queue: docker-builder

  - wait
  - command: scripts/build.sh
    name: "Build :docker: images"
    agents:
      queue: docker-builder

  - wait
  - command: scripts/test_all_images.sh
    name: "Test :allthethings:"
    agents:
      queue: docker-builder

  - wait
  - command: scripts/release.sh
    name: "Push images to DockerHub :rocket:"
    branches: master
    agents:
      queue: docker-builder
